[package]
name = "sensors-ebpf"
version = "0.1.0"
edition.workspace = true

[dependencies]
sensors-common = { path = "../sensors-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "sensors"
path = "src/main.rs"
